# Generated by Django 3.2.22 on 2023-12-02 04:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_alter_merchandisemod_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandisemod',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dsqr7dgjt/image/upload/v1700499377/jnepz9qayczlbb0gqvao.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
