# Generated by Django 3.2.22 on 2024-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_alter_merchandisemod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandisemod',
            name='image',
        ),
    ]
