# Generated by Django 3.2.22 on 2024-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_remove_merchandisemod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisemod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
