# Generated by Django 3.2.22 on 2023-11-17 15:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Artist Name')),
                ('song_title', models.CharField(max_length=100, verbose_name='Song Title')),
                ('song_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='song_file')),
                ('song_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='song_image')),
            ],
        ),
    ]
