# Generated by Django 3.2.22 on 2024-01-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmod',
            name='song_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
