# Generated by Django 3.2.22 on 2023-11-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicModel',
            new_name='MusicMod',
        ),
    ]
