# Generated by Django 3.2.22 on 2023-11-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('musicapp', '0002_rename_musicmodel_musicmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmod',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicmod',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CommentMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musicapp.musicmod')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='profiles.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
