# Generated by Django 3.2.22 on 2023-11-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20231122_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmod',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='musicmod',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
    ]
